#define TORSO_WIDTH 2.0
#define TORSO_HEIGHT 6.0
#define TORSO_DEPTH 4.0

#define HEAD_RADIUS 2.0
#define HEAD_XSCALE 1.0
#define HEAD_YSCALE 1.5
#define HEAD_ZSCALE 1.0
#define HEAD_OFFSET 2.75

#define EAR_RADIUS 2.0
#define EAR_HEIGHT 0.5
#define EAR_XSCALE 0.75
#define EAR_ZSCALE 1.15
#define EAR_OFFSET (((HEAD_RADIUS * HEAD_YSCALE) / 2.0) - (EAR_HEIGHT * 2.25))

#define UPPER_ARM_WIDTH 1.5
#define UPPER_ARM_HEIGHT 5.0
#define UPPER_ARM_DEPTH 1.5
#define UPPER_ARM_SHOULDER_RATIO 0.25

#define LOWER_ARM_WIDTH 1.5
#define LOWER_ARM_HEIGHT 5.0
#define LOWER_ARM_DEPTH 1.5
#define LOWER_ARM_ELBOW_RATIO 0.65

#define UPPER_LEG_WIDTH 2.5
#define UPPER_LEG_HEIGHT 6.0
#define UPPER_LEG_DEPTH 2.5
#define UPPER_LEG_XOFFSET ((TORSO_WIDTH / 2.0f) + 1.0)

#define LOWER_LEG_WIDTH 1.75
#define LOWER_LEG_HEIGHT 4.0
#define LOWER_LEG_DEPTH 1.75
#define LOWER_LEG_XOFFSET UPPER_LEG_XOFFSET

#define TEAPOT_X (LOWER_ARM_HEIGHT+UPPER_ARM_HEIGHT+TORSO_DEPTH)
#define TEAPOT_Y (LOWER_LEG_HEIGHT+(UPPER_LEG_HEIGHT/2.0f))
#define TEAPOT_Z 4.0f
#define TEAPOT_SCALE 3.0f
#define BOX_SCALE 10.0f
