#define TORSO_WIDTH 2.0
#define TORSO_HEIGHT 8.0
#define TORSO_DEPTH 4.0

#define HEAD_RADIUS 2.0
#define HEAD_XSCALE 0.5
#define HEAD_YSCALE 1.0
#define HEAD_ZSCALE 0.5

#define EAR_RADIUS 0.5
#define EAR_HEIGHT 0.75

#define UPPER_ARM_WIDTH 1.5
#define UPPER_ARM_HEIGHT 3.0
#define UPPER_ARM_DEPTH 1.5

#define LOWER_ARM_WIDTH 1.0
#define LOWER_ARM_HEIGHT 3.0
#define LOWER_ARM_DEPTH 1.0

#define UPPER_LEG_WIDTH 1.5
#define UPPER_LEG_HEIGHT 4.0
#define UPPER_LEG_DEPTH 1.5

#define LOWER_LEG_WIDTH 1.0
#define LOWER_LEG_HEIGHT 4.0
#define LOWER_LEG_DEPTH 1.0
#define TEAPOT_X (LOWER_ARM_HEIGHT+UPPER_ARM_HEIGHT+TORSO_DEPTH)
#define TEAPOT_Y (LOWER_LEG_HEIGHT+UPPER_LEG_HEIGHT)
